export default function Home() {
          return (
              <main className="min-h-screen bg-white text-gray-900">
                    <header className="border-b border-gray-100 bg-white">
                            <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5">
                                      <a href="/" className="text-2xl font-bold tracking-tight">
                                                  Rivo Surveys
                                                            </a>

                                                                      <nav className="flex items-center gap-3">
                                                                                  <a
                                                                                                href="/login"
                                                                                                              className="rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100"
                                                                                                                          >
                                                                                                                                        Sign in
                                                                                                                                                    </a>

                                                                                                                                                                <a
                                                                                                                                                                              href="/register"
                                                                                                                                                                                            className="rounded-lg bg-black px-5 py-2.5 text-sm font-medium text-white hover:bg-gray-800"
                                                                                                                                                                                                        >
                                                                                                                                                                                                                      Create account
                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                            </nav>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                          </header>

                                                                                                                                                                                                                                                                <section className="border-b border-gray-100">
                                                                                                                                                                                                                                                                        <div className="mx-auto max-w-7xl px-6 py-24 text-center md:py-32">
                                                                                                                                                                                                                                                                                  <div className="mx-auto max-w-3xl">
                                                                                                                                                                                                                                                                                              <p className="text-sm font-semibold uppercase tracking-wider text-gray-500">
                                                                                                                                                                                                                                                                                                            Rivo Surveys
                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                    <h1 className="mt-5 text-5xl font-bold tracking-tight text-gray-950 md:text-7xl">
                                                                                                                                                                                                                                                                                                                                                  Get Paid for Your Opinions with Online Surveys.
                                                                                                                                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                                                                                                                                          <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-gray-600 md:text-xl">
                                                                                                                                                                                                                                                                                                                                                                                        Complete paid online surveys, share your opinions, earn Rivo Coins,
                                                                                                                                                                                                                                                                                                                                                                                                      and manage your rewards from one simple account.
                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-lg bg-black px-7 py-3.5 font-medium text-white hover:bg-gray-800"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Start earning
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/login"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-lg border border-gray-300 px-7 py-3.5 font-medium text-gray-900 hover:bg-gray-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Sign in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <section className="mx-auto max-w-7xl px-6 py-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid gap-6 md:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="rounded-2xl border border-gray-200 bg-gray-50 p-7">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-black text-sm font-bold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        01
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="mt-6 text-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Create your account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-3 leading-7 text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Sign up for free and create your Rivo Surveys profile.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-2xl border border-gray-200 bg-gray-50 p-7">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-black text-sm font-bold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              02
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="mt-6 text-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Complete surveys
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="mt-3 leading-7 text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Find available surveys that match your profile and complete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        them.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="rounded-2xl border border-gray-200 bg-gray-50 p-7">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-black text-sm font-bold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  03
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="mt-6 text-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Earn rewards
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-3 leading-7 text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Track your earnings and request withdrawals when you're
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            eligible.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="border-t border-gray-100 bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mx-auto max-w-4xl px-6 py-20 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-3xl font-bold tracking-tight text-gray-950 md:text-4xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        <section className="border-b border-gray-100 bg-gray-50">
          <div className="mx-auto max-w-5xl px-6 py-20 md:py-24">
            <div className="mx-auto max-w-3xl text-center">
              <p className="text-sm font-semibold uppercase tracking-wider text-gray-500">
                Paid Surveys FAQ
              </p>

              <h2 className="mt-3 text-3xl font-bold tracking-tight text-gray-950 md:text-4xl">
                Frequently asked questions about online surveys
              </h2>

              <p className="mt-4 text-gray-600">
                Learn how Rivo Surveys works, how you can earn rewards, and what
                to expect when completing online surveys.
              </p>
            </div>

            <div className="mx-auto mt-10 max-w-3xl space-y-4">
              <details className="rounded-2xl border border-gray-200 bg-white p-6">
                <summary className="cursor-pointer font-semibold text-gray-950">
                  What are paid online surveys?
                </summary>
                <p className="mt-3 leading-7 text-gray-600">
                  Paid online surveys are research questionnaires where
                  participants share their opinions and feedback. Rivo Surveys
                  provides available survey opportunities and rewards eligible
                  participants for completed surveys.
                </p>
              </details>

              <details className="rounded-2xl border border-gray-200 bg-white p-6">
                <summary className="cursor-pointer font-semibold text-gray-950">
                  How can I earn money from surveys?
                </summary>
                <p className="mt-3 leading-7 text-gray-600">
                  Create a free Rivo Surveys account, explore available survey
                  opportunities, complete surveys that match your profile, and
                  earn Rivo Coins when eligible activities are completed.
                </p>
              </details>

              <details className="rounded-2xl border border-gray-200 bg-white p-6">
                <summary className="cursor-pointer font-semibold text-gray-950">
                  Is Rivo Surveys free to join?
                </summary>
                <p className="mt-3 leading-7 text-gray-600">
                  Yes. Creating a Rivo Surveys account is free. You can then
                  explore available online surveys and participate in eligible
                  research opportunities.
                </p>
              </details>

              <details className="rounded-2xl border border-gray-200 bg-white p-6">
                <summary className="cursor-pointer font-semibold text-gray-950">
                  Where can I find available surveys?
                </summary>
                <p className="mt-3 leading-7 text-gray-600">
                  Visit the surveys page to see currently available survey
                  opportunities and learn more about completing surveys through
                  Rivo Surveys.
                </p>
              </details>
            </div>
          </div>
        </section>

Ready to get started?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-4 text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Create your Rivo Surveys account and start exploring available
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                surveys.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="mt-8 inline-block rounded-lg bg-black px-7 py-3.5 font-medium text-white hover:bg-gray-800"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Create your account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <footer className="border-t border-gray-100 bg-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-8 text-sm text-gray-500 sm:flex-row sm:items-center sm:justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-col gap-1">
              <p>© 2026 Rivo Surveys. All rights reserved.</p>
              <p>
                Support:{" "}
                <a
                  href="mailto:rivosurveys@gmail.com"
                  className="font-medium text-gray-700 hover:text-black"
                >
                  rivosurveys@gmail.com
                </a>
              </p>
            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="/login" className="hover:text-gray-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sign in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="/register" className="hover:text-gray-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Create account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }